package AppSTC;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pjuarezc
 */
public class FormularioAlarmadoSTC extends javax.swing.JFrame {

    ButtonGroup btnGr;
    
    public FormularioAlarmadoSTC() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imag/icon.jpg")).getImage());
        txtId_STC.setVisible(false);
        btnGr = new ButtonGroup();
        btnGr.add(rbNIF);
        btnGr.add(rbNIE);
        btnGr.add(rbCIF);
        cargarTabla();
        cargarTablaHistorial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlarmadoSTC = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rbNIF = new javax.swing.JRadioButton();
        rbNIE = new javax.swing.JRadioButton();
        rbCIF = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtNIF_NIE_CIF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMSISDN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTarifaActual = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTarifaDestino = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtJiraCC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtComentarios = new javax.swing.JTextField();
        txtId_STC = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAlarmadoSTCHistorial = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Massive STC");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ALARMADO MASSIVE STCs");

        tblAlarmadoSTC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_STC", "Tipo", "NIF/NIE/CIF", "MSISDN", "Tarifa Actual", "Tarifa Destino", "JiraCC", "Comentarios"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAlarmadoSTC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlarmadoSTCMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAlarmadoSTC);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tipo:");

        rbNIF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbNIF.setText("NIF");

        rbNIE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbNIE.setText("NIE");

        rbCIF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbCIF.setText("CIF");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("NIF/NIE/CIF:");

        txtNIF_NIE_CIF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("MSISDN:");

        txtMSISDN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tarifa Actual:");

        txtTarifaActual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Tarifa Destino:");

        txtTarifaDestino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("JiraCC:");

        txtJiraCC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Comentarios:");

        txtComentarios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtTarifaActual))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTarifaDestino)
                            .addComponent(txtJiraCC)
                            .addComponent(txtComentarios)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbNIF)
                                .addGap(61, 61, 61)
                                .addComponent(rbNIE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbCIF)
                                .addGap(26, 26, 26)
                                .addComponent(txtId_STC, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtMSISDN)
                            .addComponent(txtNIF_NIE_CIF)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addGap(27, 27, 27)
                        .addComponent(btnModificar)
                        .addGap(28, 28, 28)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(btnLimpiar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rbNIF)
                    .addComponent(rbNIE)
                    .addComponent(rbCIF)
                    .addComponent(txtId_STC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNIF_NIE_CIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMSISDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTarifaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTarifaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtJiraCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar))
                .addGap(47, 47, 47))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Historial");

        tblAlarmadoSTCHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_STC", "Tipo", "NIF/NIE/CIF", "MSISDN", "Tarifa Actual", "Tarifa Destino", "JiraCC", "Comentario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblAlarmadoSTCHistorial);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       String Tipo ;
       if(rbNIF.isSelected()== true){
           Tipo = "NIF";
       }else if(rbNIE.isSelected()== true){
           Tipo = "NIE";
       }else if(rbCIF.isSelected()== true){
           Tipo = "CIF";
       }else {
           Tipo = "NIF";
       }
       String NIF_NIE_CIF = txtNIF_NIE_CIF.getText();
       String MSISDN = txtMSISDN.getText();
       String TarifaActual = txtTarifaActual.getText();
       String TarifaDestino = txtTarifaDestino.getText();
       String JiraCC = txtJiraCC.getText();
       String Comentarios = txtComentarios.getText();
       
       try{
           Connection con = Conexion.getConexion();
           PreparedStatement ps = con.prepareStatement("INSERT INTO AlarmadoSTC(Tipo,NIF_NIE_CIF,MSISDN,Tarifa_Actual,Tarifa_Destino,JiraCC,Comentarios, activo) VALUES (?,?,?,?,?,?,?,?)");
           ps.setString(1, Tipo);
           ps.setString(2, NIF_NIE_CIF);
           ps.setString(3, MSISDN);
           ps.setString(4, TarifaActual);
           ps.setString(5, TarifaDestino);
           ps.setString(6, JiraCC);
           ps.setString(7, Comentarios);
           ps.setInt(8, 1);
           ps.executeUpdate();
           JOptionPane.showMessageDialog(null, "Registro guardado");
           limpiar();
           cargarTabla();
           
       } catch(SQLException e){
           JOptionPane.showMessageDialog(null, e.toString());
       }
       
       
       
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblAlarmadoSTCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlarmadoSTCMouseClicked
        
        try{
            int fila = tblAlarmadoSTC.getSelectedRow();
            int Id_STC = Integer.parseInt(tblAlarmadoSTC.getValueAt(fila, 0).toString());
            PreparedStatement ps;
            ResultSet rs;
            
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("select Tipo,NIF_NIE_CIF,MSISDN,Tarifa_Actual,Tarifa_Destino,JiraCC,Comentarios from AlarmadoSTC where Id_STC=?");
            ps.setInt(1, Id_STC);
            rs = ps.executeQuery();
            
            while(rs.next()){
                txtId_STC.setText(String.valueOf(Id_STC));
                txtNIF_NIE_CIF.setText(rs.getString("NIF_NIE_CIF"));
                txtMSISDN.setText(rs.getString("MSISDN"));
                txtTarifaActual.setText(rs.getString("Tarifa_Actual"));
                txtTarifaDestino.setText(rs.getString("Tarifa_Destino"));
                txtJiraCC.setText(rs.getString("JiraCC"));
                txtComentarios.setText(rs.getString("Comentarios"));
                if(rs.getString("Tipo").equals("NIF")){
                    rbNIF.setSelected(true);
                } else if(rs.getString("Tipo").equals("NIE")){
                    rbNIE.setSelected(true);
                } else if(rs.getString("Tipo").equals("CIF")){
                    rbCIF.setSelected(true);
                }
            }
            
        } catch(SQLException e){
           JOptionPane.showMessageDialog(null, e.toString());
        
        }
    }//GEN-LAST:event_tblAlarmadoSTCMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
       
       int Id_STC = Integer.parseInt(txtId_STC.getText());
       String Tipo ;
       if(rbNIF.isSelected()== true){
           Tipo = "NIF";
       }else if(rbNIE.isSelected()== true){
           Tipo = "NIE";
       }else if(rbCIF.isSelected()== true){
           Tipo = "CIF";
       }else {
           Tipo = "NIF";
       }
       String NIF_NIE_CIF = txtNIF_NIE_CIF.getText();
       String MSISDN = txtMSISDN.getText();
       String TarifaActual = txtTarifaActual.getText();
       String TarifaDestino = txtTarifaDestino.getText();
       String JiraCC = txtJiraCC.getText();
       String Comentarios = txtComentarios.getText();
       
       try{
           Connection con = Conexion.getConexion();
           PreparedStatement ps = con.prepareStatement("UPDATE AlarmadoSTC SET Tipo=?,NIF_NIE_CIF=?,MSISDN=?,Tarifa_Actual=?,Tarifa_Destino=?,JiraCC=?,Comentarios=? where Id_STC=?");
           ps.setString(1, Tipo);
           ps.setString(2, NIF_NIE_CIF);
           ps.setString(3, MSISDN);
           ps.setString(4, TarifaActual);
           ps.setString(5, TarifaDestino);
           ps.setString(6, JiraCC);
           ps.setString(7, Comentarios);
           ps.setInt(8, Id_STC);
           ps.executeUpdate();
           JOptionPane.showMessageDialog(null, "Registro modificado");
           limpiar();
           cargarTabla();
           
       } catch(SQLException e){
           JOptionPane.showMessageDialog(null, e.toString());
       }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int Id_STC = Integer.parseInt(txtId_STC.getText());
             
       try{
           Connection con = Conexion.getConexion();
           PreparedStatement ps = con.prepareStatement("DELETE FROM AlarmadoSTC where Id_STC=?");
           ps.setInt(1, Id_STC);
           ps.executeUpdate();
           JOptionPane.showMessageDialog(null, "Registro eliminado");
           limpiar();
           cargarTabla();
           
       } catch(SQLException e){
           JOptionPane.showMessageDialog(null, e.toString());
       }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void limpiar(){
        txtId_STC.setText("");
        txtNIF_NIE_CIF.setText("");
        txtMSISDN.setText("");
        txtTarifaActual.setText("");
        txtTarifaDestino.setText("");
        txtJiraCC.setText("");
        txtComentarios.setText("");
        btnGr.clearSelection();
    
    }
    
    private void cargarTabla(){
        DefaultTableModel modeloTabla = (DefaultTableModel) tblAlarmadoSTC.getModel();
        modeloTabla.setRowCount(0);
        
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
        
        /*int[] anchos = {10, 50, 12, 12, 100};
        for(int i=0; i< tblAlarmadoSTC.getColumnCount(); i++){
            tblAlarmadoSTC.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }*/
        
        try{
            
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("select Id_STC,Tipo,NIF_NIE_CIF,MSISDN,Tarifa_Actual,Tarifa_Destino,JiraCC,Comentarios from AlarmadoSTC");
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for(int indice=0; indice<columnas; indice++){
                    fila[indice] = rs.getObject(indice + 1);
                }
                modeloTabla.addRow(fila);
            }
            
        } catch(SQLException e){
           JOptionPane.showMessageDialog(null, e.toString());
        
        }
        
        
    }
    
    
    
    private void cargarTablaHistorial(){
        DefaultTableModel modeloTabla2 = (DefaultTableModel) tblAlarmadoSTCHistorial.getModel();
        modeloTabla2.setRowCount(0);
        
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
        
        /*int[] anchos = {10, 50, 12, 12, 100};
        for(int i=0; i< tblAlarmadoSTC.getColumnCount(); i++){
            tblAlarmadoSTC.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }*/
        
        try{
            
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("select Id_STC,Tipo,NIF_NIE_CIF,MSISDN,Tarifa_Actual,Tarifa_Destino,JiraCC,Comentarios from AlarmadoSTCHistorial");
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for(int indice=0; indice<columnas; indice++){
                    fila[indice] = rs.getObject(indice + 1);
                }
                modeloTabla2.addRow(fila);
            }
            
        } catch(SQLException e){
           JOptionPane.showMessageDialog(null, e.toString());
        
        }
        
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioAlarmadoSTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioAlarmadoSTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioAlarmadoSTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioAlarmadoSTC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioAlarmadoSTC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbCIF;
    private javax.swing.JRadioButton rbNIE;
    private javax.swing.JRadioButton rbNIF;
    private javax.swing.JTable tblAlarmadoSTC;
    private javax.swing.JTable tblAlarmadoSTCHistorial;
    private javax.swing.JTextField txtComentarios;
    private javax.swing.JTextField txtId_STC;
    private javax.swing.JTextField txtJiraCC;
    private javax.swing.JTextField txtMSISDN;
    private javax.swing.JTextField txtNIF_NIE_CIF;
    private javax.swing.JTextField txtTarifaActual;
    private javax.swing.JTextField txtTarifaDestino;
    // End of variables declaration//GEN-END:variables
}
